### PR TITLE
creating branch and commiting my code to pechandacode. adding html fi…

### PR DESCRIPTION
**Pull request by pechandav**
…le/ UI

### CODE REVIEW

**Review by sheikb08 — APPROVED** [review]

**Review by sheikb08 — COMMENTED** [review]
We should add the style piece to to a CSS file

**Review by sheikb08 — CHANGES_REQUESTED** [review]
Lets move the styling component to a CSS file.

**Review by sheikb08 — COMMENTED** [review]
Adding CSS file

**Review by pechandav — COMMENTED** [review]
Good

**Review by pechandav — COMMENTED** [review]
Done

**Review by sheikb08 — APPROVED** [review]

**Pull request merged**
