### PR TITLE
Update readme file

### PR DESCRIPTION
**Pull request by GauriKhandke**
Updated README.md file

### CODE REVIEW

**Review by sheikb08 — CHANGES_REQUESTED** [review]
Please update the screenshots with the new UI.

**Comment by GauriKhandke** [comment]
> Please update the screenshots with the new UI.

New UI pushed in branch menuCollapse  with commit id 2a2687679884bc142e3b37daf03a1f9fd9bf5fad is not working as expected. I don't think we should go with these last minute changes as we have just last night left before presentation. I am attaching screenshot along with this.

**In mobile I have following concerns:**

1. UI is not aligned to right side properly
2. Menu is not collapsing (this was the main purpose of code in your new branch)
3. Menu text is not visible.
New UI

Our latest code in master branch with commit id 5d648bd92ed8ab0bc4071be182d625c66f4dedff is fully functional. So let's use that.

**Comment by sheikb08** [comment]
Everything has been FULLY functional and responsive for ~24 hours now. Please let me know if you want to opt out of this piece of the project as I would hate to get a bad grade due to UI preference.

**Comment by GauriKhandke** [comment]
> Everything has been FULLY functional and responsive for ~24 hours now. Please let me know if you want to opt out of this piece of the project as I would hate to get a bad grade due to UI preference.

Current code deployed isn't responsive properly on Mobile devices. It is not aligned to right side. Please find attached screenshot for your reference. 
I can't proceed with updating this pull request with current UI. 

I am closing this pull request. 
@Brandon: You can create a new pull request for new README file.

Screen Shot 2020-08-01 at 3 56 50 PM

**Pull request closed without merging**
